name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Цей pipeline запускається, коли є пуш в основну гілку

jobs:
  deploy:
    runs-on: ubuntu-latest  # Вказуємо, що завдання має виконуватись на останньому доступному Ubuntu

    steps:
      - uses: actions/checkout@v2  # Крок для клонування вашого репозиторію
      - name: Збірка  # Вказуємо крок для збірки
        run: mvn clean install  # Виконуємо команду для збірки Maven проєкту

      - name: Розгортання  # Крок для симуляції розгортання
        run: echo "Розгортання завершено."  # Виводимо повідомлення про завершення розгортання
